---
title: "Monthly Risk Adjusted Returns"
author: "Dustin Lind"
date: "3/29/2022"
output: html_document
---

```{r}
library(tidyverse)
library(haven)
library(stargazer)
```

```{r}
ff_factors_monthly <- read_csv("F-F_Research_Data_5_Factors_2x3.csv",
                       skip = 4, # top of the file reports data sources
                       col_names = c("date",
                                     "mkt-rf",
                                     "smb",
                                     "hml",
                                     "rmw",
                                     "cma",
                                     "rf"),
                       n_max  = 703) # the bottom of the csv file reports annual factors instead of monthly factors


portfolio_returns_monthly <- read_dta("portfolio_construction_monthly.dta")
```

```{r}
CRSP_Monthly <- read_dta("CRSP_MS_1962_2020.dta")

CRSP_Monthly2 <- CRSP_Monthly %>%
  select(-c(SHRCD,EXCHCD,PERMCO,RET)) %>%
  mutate(year = as.numeric(format(date, '%Y'))) %>%
  mutate(month = as.numeric(format(date, '%m'))) %>%
  filter(!(year < 1980)) %>%
  filter(month == 6)

market_cap <- CRSP_Monthly2 %>% 
  mutate(mkt_cap = abs(PRC)*SHROUT) %>%
  select(-c(date,PRC,SHROUT,month))
```

```{r}
portfolio_returns_monthly_mktcap <- portfolio_returns_monthly %>%
  left_join(market_cap, by = c("PERMNO" = "PERMNO", "year" = "year"))
```

```{r}
ff_factors_monthly2 <- ff_factors_monthly %>%
  mutate(year = as.numeric(substr(date, 1, 4))) %>%
  mutate(month = as.numeric(substr(date, 5, 6))) %>%
  arrange(year, month)

ff_factors_monthly3 <- ff_factors_monthly2 %>%
  mutate("mkt-rf" = `mkt-rf`/100,
         "smb" = smb/100,
         "hml" = hml/100,
         "rmw" = rmw/100,
         "cma" = cma/100,
         "rf" = rf/100
  )
```

```{r}
good_sga <- portfolio_returns_monthly_mktcap %>%
  filter(goodSGA == 1) %>%
  select(-badSGA)

bad_sga <- portfolio_returns_monthly_mktcap %>%
  filter(badSGA == 1) %>%
  select(-goodSGA)
```

---------------------------------------

## GoodSGA Analysis
```{r}
ff_monthly_goodSGA_returns <- good_sga %>%
  group_by(year,month_temp) %>%
  summarize(year_temp, EW_monthly_ret = mean(RET), W_monthly_ret = weighted.mean(RET, mkt_cap)) %>%
  distinct() %>%
  left_join(ff_factors_monthly3, by = c("year_temp" = "year", "month_temp" = "month")) %>%
  mutate("r_excess_EW" = EW_monthly_ret - rf,
         "r_excess_W" = W_monthly_ret - rf) %>%
  filter(!(year_temp < 1980)) %>%
  filter(!(year_temp==1980 & month_temp < 7)) %>%
  filter(!(year_temp > 2020)) %>%
  filter(!(year_temp==2020 & month_temp > 6)) %>%
  arrange(year_temp,month_temp)

```

# Equal Weight
```{r}
goodSGA_five_factor_reg_EW <- lm(r_excess_EW ~ `mkt-rf` + smb + hml + rmw + cma, data = ff_monthly_goodSGA_returns)
summary(goodSGA_five_factor_reg_EW)
```
```{r}
goodSGA_three_factor_reg_EW <- lm(r_excess_EW ~ `mkt-rf` + smb + hml, data = ff_monthly_goodSGA_returns)
summary(goodSGA_three_factor_reg_EW)
```
```{r}
goodSGA_excess_reg_EW <- lm(r_excess_EW ~ `mkt-rf`, data = ff_monthly_goodSGA_returns)
summary(goodSGA_excess_reg_EW)
```


# Equity Weight
```{r}
goodSGA_five_factor_reg_W <- lm(r_excess_W ~ `mkt-rf` + smb + hml + rmw + cma, data = ff_monthly_goodSGA_returns)
summary(goodSGA_five_factor_reg_W)
```
```{r}
goodSGA_three_factor_reg_W <- lm(r_excess_W ~ `mkt-rf` + smb + hml, data = ff_monthly_goodSGA_returns)
summary(goodSGA_three_factor_reg_W)
```
```{r}
goodSGA_excess_reg_W <- lm(r_excess_W ~ `mkt-rf`, data = ff_monthly_goodSGA_returns)
summary(goodSGA_excess_reg_W)
```

------------------------------------

## Bad SG&A Analysis

```{r}
ff_monthly_badSGA_returns <- bad_sga %>%
  group_by(year,month_temp) %>%
  summarize(year_temp, EW_monthly_ret = mean(RET), W_monthly_ret = weighted.mean(RET, mkt_cap)) %>%
  distinct() %>%
  left_join(ff_factors_monthly3, by = c("year_temp" = "year", "month_temp" = "month")) %>%
  mutate("r_excess_EW" = EW_monthly_ret - rf,
         "r_excess_W" = W_monthly_ret - rf) %>%
  filter(!(year_temp < 1980)) %>%
  filter(!(year_temp==1980 & month_temp < 7)) %>%
  filter(!(year_temp > 2020)) %>%
  filter(!(year_temp==2020 & month_temp > 6)) %>%
  arrange(year_temp,month_temp)

```

```{r}
badSGA_five_factor_reg_EW <- lm(r_excess_EW ~ `mkt-rf` + smb + hml + rmw + cma, data = ff_monthly_badSGA_returns)
summary(badSGA_five_factor_reg_EW)
```
```{r}
badSGA_three_factor_reg_EW <- lm(r_excess_EW ~ `mkt-rf` + smb + hml, data = ff_monthly_badSGA_returns)
summary(badSGA_three_factor_reg_EW)
```
```{r}
badSGA_excess_reg_EW <- lm(r_excess_EW ~ `mkt-rf`, data = ff_monthly_badSGA_returns)
summary(badSGA_excess_reg_EW)
```

# Equity Weighted
```{r}
badSGA_five_factor_reg_W <- lm(r_excess_W ~ `mkt-rf` + smb + hml + rmw + cma, data = ff_monthly_badSGA_returns)
summary(badSGA_five_factor_reg_W)
```
```{r}
badSGA_three_factor_reg_W <- lm(r_excess_W ~ `mkt-rf` + smb + hml, data = ff_monthly_badSGA_returns)
summary(badSGA_three_factor_reg_W)
```
```{r}
badSGA_excess_reg_W <- lm(r_excess_W ~ `mkt-rf`, data = ff_monthly_badSGA_returns)
summary(badSGA_excess_reg_W)
```

-------------------------------------------------


## Spread Analysis
```{r}
bad_sga_summarized <- bad_sga %>%
  group_by(year, month_temp) %>%
  summarize(year_temp,EW_monthly_ret_badSGA = mean(RET), W_monthly_ret_badSGA = weighted.mean(RET, mkt_cap)) %>%
  distinct()

good_sga_summarized <- good_sga %>%
  group_by(year, month_temp) %>%
  summarize(year_temp,EW_monthly_ret_goodSGA = mean(RET), W_monthly_ret_goodSGA = weighted.mean(RET, mkt_cap)) %>%
  distinct()

ff_monthly_spread_returns <- good_sga_summarized %>%
  left_join(bad_sga_summarized, by = c("year","month_temp","year_temp")) %>%
  left_join(ff_factors_monthly3, by = c("year_temp" = "year", "month_temp" = "month")) %>%
  mutate("spread_r_EW" = EW_monthly_ret_goodSGA - EW_monthly_ret_badSGA,
         "spread_r_W" = W_monthly_ret_goodSGA - W_monthly_ret_badSGA) %>%
  filter(!(year_temp < 1980)) %>%
  filter(!(year_temp==1980 & month_temp < 7)) %>%
  filter(!(year_temp > 2020)) %>%
  filter(!(year_temp==2020 & month_temp > 6)) %>%
  arrange(year_temp,month_temp)
```

# Equal Weighted
```{r}
spread_five_factor_reg_EW <- lm(spread_r_EW ~ `mkt-rf` + smb + hml + rmw + cma, data = ff_monthly_spread_returns)
summary(spread_five_factor_reg_EW)
```
```{r}
spread_three_factor_reg_EW <- lm(spread_r_EW ~ `mkt-rf` + smb + hml, data = ff_monthly_spread_returns)
summary(spread_three_factor_reg_EW)
```
```{r}
spread_excess_reg_EW <- lm(spread_r_EW ~ `mkt-rf`, data = ff_monthly_spread_returns)
summary(spread_excess_reg_EW)
```

# Equity Weighted
```{r}
spread_five_factor_reg_W <- lm(spread_r_W ~ `mkt-rf` + smb + hml + rmw + cma, data = ff_monthly_spread_returns)
summary(spread_five_factor_reg_W)
```
```{r}
spread_three_factor_reg_W <- lm(spread_r_W ~ `mkt-rf` + smb + hml, data = ff_monthly_spread_returns)
summary(spread_three_factor_reg_W)
```
```{r}
spread_excess_reg_W <- lm(spread_r_W ~ `mkt-rf`, data = ff_monthly_spread_returns)
summary(spread_excess_reg_W)
```

--------------------------------------------

## Regression tables

# Equal Weight
```{r}
stargazer(badSGA_five_factor_reg_EW,goodSGA_five_factor_reg_EW,spread_five_factor_reg_EW,
          title = "Equal-weight portfolio's five-factor loadings",
          align = TRUE,
          column.labels = c("BadSG\\&A", "GoodSG\\&A", "Spread"),
          dep.var.caption = "",
          dep.var.labels.include = FALSE,
          covariate.labels = c("b", "s", "h", "r", "c"),
          omit = c("Constant"),
          keep.stat = c("n", "rsq")
          )
```

# Equity Weighted
```{r}
stargazer(badSGA_five_factor_reg_W,goodSGA_five_factor_reg_W,spread_five_factor_reg_W,
          title = "Equity-weighted portfolio's five-factor loadings",
          align = TRUE,
          column.labels = c("BadSG\\&A", "GoodSG\\&A", "Spread"),
          dep.var.caption = "",
          dep.var.labels.include = FALSE,
          covariate.labels = c("b", "s", "h", "r", "c"),
          omit = c("Constant"),
          keep.stat = c("n", "rsq")
          )
```